# Generated by Django 5.1.6 on 2025-02-22 19:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="Egitim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("lecturer", models.CharField(max_length=150)),
                ("education_provider", models.CharField(max_length=50)),
                ("lecturer_provider", models.CharField(max_length=100)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="egitimler", to="mysite.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Eğitimler",
            },
        ),
        migrations.CreateModel(
            name="Okul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("level", models.CharField(max_length=150)),
                ("branch", models.CharField(max_length=150)),
                ("status", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("city", models.CharField(max_length=50)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="okullar", to="mysite.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Okullar",
            },
        ),
        migrations.CreateModel(
            name="Proje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="uploads")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="projeler", to="mysite.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projeler",
            },
        ),
    ]
