# Generated by Django 5.1.6 on 2025-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="egitim",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="okul",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="proje",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
